# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='unite',
            new_name='unit',
        ),
        migrations.AlterModelTable(
            name='books',
            table='s_books',
        ),
    ]
