# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '待评价'), (3, '待收货'), (2, '代发货'), (5, '已完成'), (1, '待支付')], default=1, verbose_name='订单状态'),
        ),
    ]
